[project]
name = "2025-03-mle-workshop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "click>=8.1.8",
    "logging>=0.4.9.6",
    "numpy==1.26.4",
    "pandas>=2.2.3",
    "pyarrow>=19.0.1",
    "scikit-learn==1.2.2",
]

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "seaborn>=0.13.2",
]

[tool.uv.workspace]
members = ["day_2", "day_2/duration_pred_serve"]
